apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - prometheus/config.yaml
  - prometheus/deployment.yaml
  - prometheus/alerts.yaml
  - grafana/config.yaml
  - grafana/deployment.yaml
  - grafana/dashboards
  - exporters/node-exporter.yaml
  - exporters/kube-state-metrics.yaml
  # Note: metrics-server already exists in kube-system on OKE
