apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# cert-manager installed via: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml

resources:
  - cluster-issuer.yaml
