apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
